plugins:
  - 'prettier-plugin-solidity'
bracketSpacing: true
printWidth: 120
proseWrap: 'always'
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'all'

overrides:
  - files: '*.sol'
    options:
      parser: 'solidity-parse'
      tabWidth: 4
